export const excludeTags = [
    "meal",
    "breakfast",
    "lunch",
    "dinner",
    "snack",
    "tasty",
    "plate",
    "dish",
    "cuisine",
    "delicious",
    "restaurant",
    "eat",
    "diet",
    "gourmet",
    "healthy",
    "eating",
    "nutrition",
    "fast",
    "fat",
    "calories",
    "health",
    "traditional",
    "vegetables",
    "cooking",
    "closeup",
    "menu",
    "prepared",
    "culinary",
    "studio",
    "gastronomy",
    "culture",

// const relatedGeneralTags

    "food",
    "cooked food",
    "homemade",
    "prepared food",
    "organic",
    "ingredients",
    "kitchen",
    "tableware",
    "presentation",
    "meal prep",
    "recipe",
    "serving",
    "dining",
    "flavors",
    "taste",
    "texture",
    "nutrition facts",
    "freshness",
    "baked goods",
    "baked",
    "bakery",
    "fresh",
    "brown",
    "slice",
    "crust",
    "loaf",
    "loaf of bread"
];
